export interface ITabMap {
  [name: string]: ITabInfo;
};

export interface ITabInfo {
  content: HTMLElement;
  text: string;
  displayMulti: boolean;
  btn?: HTMLElement; // "Button" which is generated by the Tab class internally
}

/** For tabs/* files */
export interface ITabProperties {
  target: HTMLDivElement;
  text: string;
}